package Utils;

//this class will be used for testing

import java.util.Base64;
import java.security.SecureRandom;
import java.util.UUID;

public class Random {


    public static String token() {
        // Initialise the libraries and a place to store the randomly generated bytes
        SecureRandom secureRandom = new SecureRandom();
        Base64.Encoder base64Encoder = Base64.getUrlEncoder();
        byte[] randomBytes = new byte[24];

        // Generate the random bytes and return the token as a base64 encoding
        secureRandom.nextBytes(randomBytes);
        return base64Encoder.encodeToString(randomBytes);
    }


    public static String String() {
        return UUID.randomUUID().toString().replace("-", "");
    }

    public static boolean Boolean() {
        java.util.Random random = new java.util.Random();
        return random.nextBoolean();
    }

    public static int Int(int max) {
        java.util.Random random = new java.util.Random();
        return Math.abs(random.nextInt(max));
    }

}
